base/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', index, name='index'),
    path('register/', register, name='register'),
    path('login/', login_view, name='loginn'),
    path('logout/', logout_view, name='logout'),
    path('profile/', profile, name='profile'),
    path('feedback/', feedback_view, name='your_feedback_view'),
    path('chatadm/', admin_feedback_view, name='admin_feedback_view'),
    path('chatadm/<int:feedback_id>/', chat_view, name='chat_view'),
    path('chatusr/', user_chat_view, name='user_chat_view'),
    path('chatusr/<int:feedback_id>/', user_chat_detail_view, name='user_chat_detail_view'),
    path('news/', news_list, name='news_list'),
    path('news/<int:pk>/', news_detail, name='news_detail'),
    path('news/<int:news_id>/add_review/', add_review, name='add_review'),
    path('contacts/', contacts, name='contacts'),
    path('services/', services, name='services'),
    path('service/<int:id>/', service_detail, name='service_detail'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('base.urls'))
]

base/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ValidationError
from django.utils import timezone

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="Пользователь")
    bio = models.TextField(blank=True, verbose_name="Биография")
    website = models.URLField(blank=True, verbose_name="Веб-сайт")

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = "Профиль"
        verbose_name_plural = "Профили"


class Avatar(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="Пользователь")
    image = models.ImageField(upload_to='avatars/', blank=True, verbose_name="Изображение")

    class Meta:
        verbose_name = "Аватар"
        verbose_name_plural = "Аватары"


class UserSettings(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="Пользователь")
    notifications_enabled = models.BooleanField(default=True, verbose_name="Уведомления включены")

    class Meta:
        verbose_name = "Настройки пользователя"
        verbose_name_plural = "Настройки пользователей"


class AdditionalInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="Пользователь")
    custom_field = models.TextField(blank=True, verbose_name="Дополнительное поле")

    class Meta:
        verbose_name = "Дополнительная информация"
        verbose_name_plural = "Дополнительная информация"


STATUS_CHOICES = [
    ('new', 'Новое'),
    ('in_progress', 'В процессе'),
    ('resolved', 'Решено'),
    ('cancelled', 'Отменено'),
]


class Feedback(models.Model): 
    name = models.CharField(max_length=100, verbose_name='Имя') 
    email = models.EmailField(verbose_name='Электронная почта') 
    phone_number = models.CharField(max_length=15, verbose_name='Номер телефона', blank=True, null=True) 
    message = models.TextField(verbose_name='Сообщение') 
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='new', verbose_name='Статус') 
    created_at = models.DateTimeField(default=timezone.now, verbose_name='Дата создания') 
    cancellation_reason = models.TextField(blank=True, null=True, verbose_name='Причина отмены') 
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f"{self.name} - {self.get_status_display()}"

    class Meta: 
        verbose_name = 'Заявки' 
        verbose_name_plural = 'Заявки'

class Chat(models.Model):
    feedback = models.ForeignKey(Feedback, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Chat between {self.user.username} and admin'

    class Meta: 
        verbose_name = 'Чаты' 
        verbose_name_plural = 'Чаты'


class News(models.Model):
    title = models.CharField(max_length=255, verbose_name="Заголовок")
    content = models.TextField(verbose_name="Содержание")
    published_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата публикации")
    image = models.ImageField(upload_to='news_images/', null=True, blank=True, verbose_name="Изображение")
    views = models.IntegerField(default=0, null=True, blank=True, verbose_name="Просмотры")
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE, verbose_name="Пользователь")
    district = models.ForeignKey('District', null=True, blank=True, on_delete=models.CASCADE, verbose_name="Район")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Новость"
        verbose_name_plural = "Новости"


class District(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True, verbose_name="Название района")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Район"
        verbose_name_plural = "Районы"


class Review(models.Model):
    news_item = models.ForeignKey(News, related_name='reviews', on_delete=models.CASCADE, verbose_name="Новость")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Пользователь")
    rating = models.IntegerField(verbose_name="Рейтинг")
    content = models.TextField(verbose_name="Комментарий")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")

    def __str__(self):
        return f"Комментарий от {self.user.username} на {self.news_item.title}"

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"


class Response(models.Model):
    review = models.ForeignKey(Review, related_name='responses', on_delete=models.CASCADE, verbose_name="Отзыв")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Пользователь")
    content = models.TextField(null=True, blank=True, verbose_name="Содержимое")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")

    def clean(self):
        super().clean()
        word_limit = 30
        word_count = len(self.content.split())
        if word_count > word_limit:
            raise ValidationError(f"Содержимое не должно превышать {word_limit} слов. Текущее количество: {word_count}.")

    def __str__(self):
        return f"Ответ от {self.user.username} на комментарий {self.review.id}"

    class Meta:
        verbose_name = "Ответ на комментарий"
        verbose_name_plural = "Ответы на комментарии"


class ServiceCategory(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True, verbose_name="Название категории")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория услуг"
        verbose_name_plural = "Категории услуг"


class Service(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True, verbose_name="Название услуги")
    description = models.TextField(verbose_name="Краткое описание", blank=True, null=True)
    image = models.ImageField(upload_to='service_images/', null=True, blank=True, verbose_name="Основное изображение")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    category = models.ForeignKey('ServiceCategory', on_delete=models.CASCADE, null=True, blank=True, related_name="services", verbose_name="Категория")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Услуга"
        verbose_name_plural = "Услуги"
        
class ServiceDetail(models.Model):
    service = models.OneToOneField(Service, on_delete=models.CASCADE, related_name="details", verbose_name="Услуга")
    full_description = models.TextField(verbose_name="Полное описание", blank=True, null=True)
    dop_text = models.TextField(null=True, blank=True, verbose_name="Дополнительный текст")

    def __str__(self):
        return f"Детали услуги: {self.service.name}"

    class Meta:
        verbose_name = "Детальная информация об услуге"
        verbose_name_plural = "Детальная информация об услуге"

class ServiceGallery(models.Model):
    service_detail = models.ForeignKey(ServiceDetail, on_delete=models.CASCADE, related_name="gallery", verbose_name="Галерея")
    image = models.ImageField(upload_to='service_gallery/', null=True, blank=True, verbose_name="Изображение")

    def __str__(self):
        return f"Изображение для {self.service_detail.service.name}"
    
    class Meta:
        verbose_name = "Изображение для услуги"
        verbose_name_plural = "Изображения для услуги"

class ServiceDetailDopInfo(models.Model):
    service_detail = models.ForeignKey(ServiceDetail, on_delete=models.CASCADE, related_name="dop_info", verbose_name="Доп. информация для услуги")
    title = models.TextField(null=True, blank=True, verbose_name="Заголовок")
    subtitle = models.TextField(null=True, blank=True,  verbose_name="Подзаголовок")
    content = models.TextField(null=True, blank=True, verbose_name="Информация")

    def __str__(self):
        title = self.title or "Без заголовка"
        service_name = self.service_detail.service.name if self.service_detail and self.service_detail.service else "Нет услуги"
        return f"{title} - {service_name}"

    class Meta:
        verbose_name = "Доп. информация для услуги"
        verbose_name_plural = "Доп. информация для услуги"

base/forms.py
from django import forms    
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm    
from django.contrib.auth.models import User 
from django.utils.translation import gettext_lazy as _  
from django.contrib.auth.forms import PasswordChangeForm 
from .models import * 


class CustomUserCreationForm(UserCreationForm):    
    username = forms.CharField(label="Имя пользователя", max_length=150, required=True)   
    email = forms.EmailField(label="Электронная почта", required=True)   
    password1 = forms.CharField(label="Пароль", widget=forms.PasswordInput, help_text=" ")   
    password2 = forms.CharField(label="Подтверждение пароля", widget=forms.PasswordInput, help_text=" ")   

class CustomAuthenticationForm(AuthenticationForm):    
    username = forms.CharField(label="Имя пользователя")   
    password = forms.CharField(label="Пароль", widget=forms.PasswordInput)   

class ProfileForm(forms.ModelForm): 
    class Meta: 
        model = Profile 
        fields = ['bio', 'website'] 
        widgets = { 
            'bio': forms.Textarea(attrs={'placeholder': 'Введите вашу биографию'}), 
        } 
        labels = {
            'bio': 'Биография',
            'website': 'Вебсайт',
        }

class AvatarForm(forms.ModelForm): 
    class Meta: 
        model = Avatar 
        fields = ['image'] 
        labels = {
            'image': 'Изображение',
        }

class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput)
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput)
    new_password2 = forms.CharField(label="Подтверждение пароля", widget=forms.PasswordInput)

    def __init__(self, user, *args, **kwargs):
        super().__init__(user, *args, **kwargs)


class UserSettingsForm(forms.ModelForm): 
    class Meta: 
        model = UserSettings 
        fields = ['notifications_enabled'] 
        labels = {
            'notifications_enabled': 'Уведомления',
        }

class AdditionalInfoForm(forms.ModelForm): 
    class Meta: 
        model = AdditionalInfo 
        fields = ['custom_field'] 
        labels = {
            'custom_field': 'Пользовательское поле',
        }

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['name', 'email', 'phone_number', 'message']

    def __init__(self, *args, **kwargs):
        super(FeedbackForm, self).__init__(*args, **kwargs)
        if self.instance and self.instance.status == 'отменён':
            self.fields['cancellation_reason'].required = True
        

class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['title', 'content', 'image', 'district']

class ResponseForm(forms.ModelForm):
    class Meta:
        model = Response
        fields = ['content']

class ChatForm(forms.ModelForm):
    class Meta:
        model = Chat
        fields = ['message']

base/templates/admin_feedback.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/feedback.css' %}">

<div class="feedback-container">
    <h1 class="feedback-title">Заявки пользователей</h1>
    <div class="feedback-list">
        {% for feedback in feedback_list %}
            <a href="{% url 'chat_view' feedback.id %}" class="feedback-item">
                <div class="feedback-info">
                    <div class="feedback-name">{{ feedback.name }}</div>
                    <div class="feedback-details">
                        <span class="feedback-date">{{ feedback.created_at|date:"d.m.Y H:i" }}</span>
                        <span class="feedback-phone">Телефон: {{ feedback.phone_number }}</span>
                    </div>
                </div>
                <div class="feedback-arrow">ᐅ</div>
            </a>
            <div class="feedback-separator"></div>
        {% endfor %}
    </div>
</div>

{% endblock %}

base/templates/base.html
<!DOCTYPE html>
{% load static %}
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
</head>

<body>
    <ul class="menu-up">
        <li>Пн-Пт с 09:00 до 18:00</li>
        <li>🕻 +7 (4922) 47-11-54</li>
        <li>🕻 +7 (901) 161-55-80</li>
    </ul>
    <ul class="menu">
        <li><div></div></li>
        <li><img src="{% static 'img/logo.png' %}" alt="Меню" class="logo-menu"></li>
        <li class="menu-toggle" id="mobile-menu"><img src="{% static 'img/menu.png' %}" alt="Меню" class="menu-button"></li>
    </ul>
    <div class="navbar">
        <a href="/" class="navbar-image imglogo"><img src="{% static 'img/logo.png' %}" alt="Логотип" class="logo"></a>
        <a href="/news" class="navbar-item">Новости</a>
        <a href="/contacts" class="navbar-item">Контакты</a>
        <a href="/services" class="navbar-item">Услуги</a>
        {% if user.is_authenticated %}
            {% if user_settings.notifications_enabled %}
            <a href="#" class="navbar-item" id="notificationsButton">Уведомления</a>
            {% endif %}
        {% endif %}
        {% if not user.is_staff %}
        <a href="/chatusr" class="navbar-item">Поддержка</a>
        {% endif %}
        {% if user.is_authenticated %}
            {% if user.is_staff %}
            <a href="/admin" class="navbar-item">Администратор</a>
            <a href="/chatadm" class="navbar-item">Чат с пользователями</a>
            {% endif %}
        <a href="/profile" class="navbar-item">{{ user.username }}</a>
        <a href="/logout" class="navbar-item"><text class="exit">Выход</text></a>
        {% else %}
        <a href="/login" class="navbar-item">Авторизироваться</a>
        <a href="/register" class="navbar-item">Зарегистрироваться</a>
        {% endif %}
    </div>
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="{% static 'js/base.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

<footer class="text-center text-lg-start bg-body-tertiary text-muted" style="background-color:#0D1226; width: 100%; position: relative;">
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom ">
        <div class="container text-center text-md-start mt-5">
            <div class="row text-center">
                <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mb-4">
                    <h2 class="text-uppercase fw-bold mb-4" style="color:#FF5F15">Телефон</h2>
                    <h3>+7 (4922) 47-11-54</h3>
                    <h3>+7 (901) 161-55-80</h3>
                </div>
                <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mb-4">
                    <h2 class="text-uppercase fw-bold mb-4" style="color:#FF5F15">Адрес</h2>
                    <h3>600027, г. Владимир,<br>Суздальский проспект,<br>д. 13а, кв. 79</h3>
                </div>
                <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mb-4">
                    <h2 class="text-uppercase fw-bold mb-4" style="color:#FF5F15">Почта</h2>
                    <h3>vladsk33@yandex.ru</h3>
                </div>
                <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mb-4">
                    <h2 class="text-uppercase fw-bold mb-4" style="color:#FF5F15">Время работы</h2>
                   <h3>Пн-Пт с 09:00 до 18:00</h3>
                </div>
            </div>
        </div>
    </section>
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
        © 2025 Copyright:
        <a class="text-reset fw-bold" href="#">VSK33.com</a>
    </div>
</footer>

</html>

base/templates/chat.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/chats.css' %}">

<div class="chat-container">
    <h1 class="chat-title">Чат с {{ feedback.name }} ({{ feedback.phone_number }})</h1>
    
    <!-- Список сообщений -->
    <div class="message-list">
        {% for chat in chats %}
            <div class="message {% if chat.user == request.user %} outgoing {% else %} incoming {% endif %}">
                <div class="message-header">
                    <span class="username">{{ chat.user.username }}</span>
                    <span class="timestamp">{{ chat.created_at|date:"H:i" }}</span>
                </div>
                <div class="message-content">{{ chat.message }}</div>
            </div>
        {% endfor %}
    </div>

    <!-- Форма отправки сообщения -->
    <form id="message-form" method="post" class="message-form">
        {% csrf_token %}
        <div class="input-group">
            {{ form.message }}
            <button type="submit" class="send-button">Отправить</button>
        </div>
    </form>
</div>

{% endblock %}

base/templates/contacts.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/contacts.css' %}">

<div class="title">
    <div class="or2">Контакты</div>
    <h2 class="ob">Как нас найти</h2>
<div>

<div class="row no-gutters" style="background-color: #121934; justify-content: center; color:#ffffff; padding:100px 0px">
    <div class="col-12 d-flex justify-content-center">
        <div class="contact-card p-4">
            <p><strong>Адрес:</strong> г. Москва, ул. Строительная, д. 10</p>
            <p><strong>Телефон:</strong> <a href="tel:+79991234567" class="contact-link">+7 (999) 123-45-67</a></p>
            <p><strong>Email:</strong> <a href="mailto:info@stroycompany.ru" class="contact-link">info@stroycompany.ru</a></p>
        </div>
    </div>
</div>
{% endblock %}

base/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

<div class="title">
    <div class="or2">Авторизация</div>
<div>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Войти</button>
</form>

{% endblock %}

base/templates/news_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/news.css' %}">

<div class="title">
    <div class="or2">Новости</div>
    <h2 class="ob">Наш Блог</h2>
<div>

<div class="row no-gutters" style="background-color:rgb(255, 255, 255); justify-content: center; color:#ffffff; padding:100px 0; overflow-x: hidden;">
    <div class="col-12">
        <div class="container mb-5">
            <!-- Форма для фильтрации -->
            <form method="GET" action="{% url 'news_list' %}" class="filter-form">
                <div class="form-group">
                    <h4 for="district" class="filter-label">Выберите район:</h4>
                    <select name="district" id="districts" class="form-control filter-select">
                        <option value="">Все районы</option>
                        {% for district in districts %}
                            <option value="{{ district.id }}" {% if request.GET.district == district.id|stringformat:"s" %}selected{% endif %}>
                                {{ district.name }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <button type="submit" class="btn btn-primary" style="background-color: #FF5F15; border: none; padding: 10px 0; border-radius: 10px; width: 100%;">
                    Применить фильтры
                </button>
            </form>
        </div>
    </div>

    {% for article in news %}
    <div class="col-12 col-sm-6 col-md-4 mr-3 ml-3">
        <div class="card news-card" style="background-image: url('{{ article.image.url }}'); background-size: cover; background-position: center; cursor: pointer;">
            <div class="card-body">
                <div class="news-overlay">
                    <h5 class="card-title">{{ article.title }}</h5>
                    <h6 class="card-text">{{ article.published_at|date:"d.m.Y" }}</h6>
                    <h6>Просмотры: {{ article.views }}</h6>
                    <a href="{% url 'news_detail' article.id %}" class="btn btn-primary mt-2">Читать полностью</a>
                </div>
                <a href="#" class="card-button">
                    <img src="{% static 'img/cart.svg' %}" alt="Иконка" class="button-icon">
                </a>
            </div>
        </div>
    </div>
    {% endfor %}

    <!-- Пагинация -->
    {% if news.has_other_pages %}
    <div class="col-12 mt-5">
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if news.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1{% if request.GET.district %}&district={{ request.GET.district }}{% endif %}" aria-label="First">
                            <span aria-hidden="true">&laquo;&laquo;</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ news.previous_page_number }}{% if request.GET.district %}&district={{ request.GET.district }}{% endif %}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}

                {% for num in news.paginator.page_range %}
                    {% if news.number == num %}
                        <li class="page-item active">
                            <span class="page-link">{{ num }}</span>
                        </li>
                    {% elif num > news.number|add:'-3' and num < news.number|add:'3' %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ num }}{% if request.GET.district %}&district={{ request.GET.district }}{% endif %}">{{ num }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if news.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ news.next_page_number }}{% if request.GET.district %}&district={{ request.GET.district }}{% endif %}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
    {% endif %}
</div>
{% endblock %}

base/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
<div class="title">
    <div class="or2">Профиль</div>
<div>
<div class="profile-container">
    <!-- Левая панель -->
    <div class="sidebar">

        <button onclick="showForm('profile')">Обновить профиль</button>
        <button onclick="showForm('avatar')">Обновить аватар</button>
        <button onclick="showForm('password')">Изменить пароль</button>
        <button onclick="showForm('settings')">Настройки уведомлений</button>
        <button onclick="showForm('additionalInfo')">Дополнительная информация</button>
    </div>

    <!-- Правая часть (формы) -->
    <div class="content">


        <!-- Форма обновления профиля -->
        <div id="profile" class="form-section hidden">
            <h3 class="form-title">Обновить профиль</h3>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ profile_form.as_p }}
                <button type="submit" name="save_profile" class="save-button">Сохранить профиль</button>
            </form>
        </div>

        <!-- Форма обновления аватара -->
        <div id="avatar" class="form-section hidden">
            {% if avatar and avatar.image %}
                <div class="avatar-section">
                    <h2 class="form-title">Ваш аватар:</h2>
                    <img src="{{ avatar.image.url }}" alt="Avatar" class="avatar-image">
                </div>
            {% else %}
                <p class="no-avatar">Аватар отсутствует.</p>
            {% endif %}
        
            <form method="POST" enctype="multipart/form-data" class="centered-form">
                {% csrf_token %}
        
                <!-- Поле для загрузки нового изображения -->
                <div class="form-field">
                    <label for="id_image">Выберите новое изображение:</label>
                    {{ avatar_form.image }}
                </div>
        
                <!-- Кнопка отправки -->
                <button type="submit" name="save_avatar" class="save-button">Сохранить аватар</button>
            </form>
        </div>

        <!-- Форма изменения пароля -->
        <div id="password" class="form-section hidden">
            <h3 class="form-title">Изменить пароль</h3>
            <form method="POST">
                {% csrf_token %}
                {{ password_form.as_p }}
                <button type="submit" name="change_password" class="save-button">Изменить пароль</button>
            </form>
        </div>

        <!-- Форма настроек уведомлений -->
        <div id="settings" class="form-section hidden">
            <h3 class="form-title">Настройки уведомлений</h3>
            <form method="POST">
                {% csrf_token %}
                {{ settings_form.as_p }}
                <button type="submit" name="save_settings" class="save-button">Сохранить настройки</button>
            </form>
        </div>

        <!-- Форма дополнительной информации -->
        <div id="additionalInfo" class="form-section hidden">
            <h3 class="form-title">Дополнительная информация</h3>
            <form method="POST">
                {% csrf_token %}
                {{ additional_info_form.as_p }}
                <button type="submit" name="save_additional_info" class="save-button">Сохранить информацию</button>
            </form>
        </div>
    </div>
</div>


<script>  
    function showForm(formId) {
    // Скрываем все формы
    document.querySelectorAll('.form-section').forEach(form => form.classList.add('hidden'));

    // Показываем выбранную форму
    const form = document.getElementById(formId);
    if (form) {
        form.classList.remove('hidden');
    }
}
</script>

{% endblock %}